### ISSUE TITLE
Deprecated metadata scheme is 1st hit in Google

### ISSUE THREAD

**Issue by tompollard** [datacite/schema#10]
The first hit in Google for "DataCite metadata" is an old version of the schema:
http://www.datacite.org/schema/DataCite-MetadataKernel_v2.0.pdf

Ideally the first hit would be:
http://schema.datacite.org

Is there anything we can do about this? Can the old scheme be removed as it is no longer supported? If not, maybe we could add a nofollow in the robots.txt?

Cheers,
Tom

**Comment by mfenner** [comment]
This is no longer an issue.
