### ISSUE TITLE
Remove 's' from OutputsManagementPlan

### ISSUE THREAD

**Issue by sarala** [datacite/schema#105]
OutputsManagementPlan under the heading 'Changes' on page https://schema.datacite.org/meta/kernel-4.4/ page should not have a 's'

Please correct 'Output**s**ManagementPlan' to 'OutputManagementPlan'.

**Comment by KellyStathis** [comment]
Fixed - will be released with the other site changes: https://github.com/datacite/schema/commit/f87ae092ff3a0e36d59920307a3fc97662d15ac4
