### ISSUE TITLE
Should "identifiers" really be required in the json schema 4.3?

### ISSUE THREAD

**Issue by edager** [datacite/schema#134]
In the json schema, the field "identifiers" is required.

However, as far as I understands, the minimal requirement is actually that there is a "doi" field (which can be automatically generated).  To me it looks like the "doi" field in the json identical to the "identifier" element in XSD (which is indeed required, and has attribute that marks it as a doi).  

Furthermore, the "identifiers" array can be empty (and in fact is in all records I've seen) e.i., the field itself may be required but having any values in there isn't, which is a bit counter intuitive if that is the case.        

So is it a mistake that identifiers is required or is it intentional? I'll gladly make a PR if it's unintentional, but don't know if it should be done here or at Invenio which seems to be the authors of the json schema, but wanted to ask here first as you're the authority on the subject.

**Comment by KellyStathis** [comment]
Hi @edager, I'd recommend submitting this to Invenio, I believe they are maintaining the JSON schemas here: https://github.com/inveniosoftware/datacite/tree/master/datacite/schemas

**Comment by tmorrell** [comment]
Yes, you can open an issue at [https://github.com/inveniosoftware/datacite/](https://github.com/inveniosoftware/datacite/tree/master/datacite/schemas). However, I don't think we'd fix it in 4.3 since the 4.3 examples put the doi in the identifiers section (for example https://github.com/inveniosoftware/datacite/blob/master/tests/data/4.3/datacite-example-affiliation-v4.json). This switch in the DataCite API to have the 'doi' field is more recent and we'd probably change it with the 4.5 version.

**Comment by KellyStathis** [comment]
Thanks @tmorrell! 

I can also confirm that the `"identifiers"` attribute is not required. See: [What is the "identifiers" attribute in the REST API?](https://support.datacite.org/docs/what-is-the-identifiers-attribute-in-the-rest-api). In short, the `"identifiers"` attribute in JSON is actually related to `"alternateIdentifiers"` property in XML, which is optional.

We recently published [DataCite XML to JSON Mapping](https://support.datacite.org/docs/datacite-xml-to-json-mapping) as well, to illustrate how each element/attribute in the XML schema is represented in JSON.

Feel free to reach out to us over at support@datacite.org if you have any questions about creating/updating or retrieving JSON via the DataCite REST API.

**Comment by edager** [comment]
@tmorrell @KellyStathis  Thanks for the quick reply and the helpful insights.  I'll close the issue here and raise it on Invenio instead, and potentially help out in the development of 4.5 if they (@tmorrell ?) want it. Thanks again!
