### ISSUE TITLE
schemaLocation in example should be fully qualified

### ISSUE THREAD

**Issue by koelnconcert** [datacite/schema#3]
Currently it is:

    xsi:schemaLocation="http://schema.datacite.org/oai/oai-1.0/ oai_datacite.xsd"

it should be:

    xsi:schemaLocation="http://schema.datacite.org/oai/oai-1.0/ http://schema.datacite.org/oai/oai-1.0/oai.xsd"

**Comment by mikejmets** [comment]
I am trying to generate oai_datacite records with python's ElementTree but keep getting "XML Parsing Error: prefix not bound to a namespace". I've tried the following 2 options with no success:
  <oai_datacite xsi:schemaLocation="http://schema.datacite.org/oai/oai-1.0/ http://schema.datacite.org/oai/oai-1.0/oai.xsd">
  <oai xsi:schemaLocation="http://schema.datacite.org/oai/oai-1.0/ http://schema.datacite.org/oai/oai-1.0/oai.xsd">
Any ideas?
