### ISSUE TITLE
Some errors in 4.1 changelog and docs

### ISSUE THREAD

**Issue by krzysztof** [datacite/schema#38]
1. In the 4.1 changelog (both on the website and the PDF) it's stated that ``Addition of new “dateInformation” subproperty for dateType`` - it should be a subproperty of "Date".

1. The website says: ``Addition of a new optional “nameType” attribute for Creator and Contributor. Controlled list: personal, organizational``, while in the PDF docs:
``Addition of a new optional attribute for creatorName and ContributorName: nameType``. It's not clear whether it's a subproperty of the top-level fields (Creator/Contributor) or the corresponding ``creator/contributorName`` subproperties. From the table it's also not clear: Under ``7 Contributor``, the ``nameType`` looks like a direct sub-property: ``7.7 nameType``, however under ``2 Creator`` it looks like a sub-property of ``2.1 creatorName``: ``2.1.1 nameType``. ~~I guess it should be either of those and kept consistent between the Contributor/Creator fields?~~ From the schema it looks like ``nameType`` is a subproperty of the ``creator/contributorName``.

1. ~~``Addition of optional lang attribute to Rights property`` - "lang" is missing from the table.~~ Misunderstood this point.

**Comment by mfenner** [comment]
`dateInformation` is indeed a subproperty of `dateType`. And `nameType is a subproperty of `creatorName`/`contributorName`.

**Comment by mfenner** [comment]
And `nameType` should be a subproperty of `contributorName`, so 7.2.1. We will fix that.
