### ISSUE TITLE
Nokogiri version out of date

### ISSUE THREAD

**Issue by richardhallett** [datacite/schema#40]
Potential security vulnerability we need update the gem file for nokogiri to something greater than 1.8.1
gem 'nokogiri', '~> 1.8.1

Need to check libraries that depend on this, might need to upgrade them too.

**Comment by mfenner** [comment]
Installing `html_proofer` 3.7.6 should fix this, as `nokogiri` is a dependency. In `Gemfile`:

```
gem 'html-proofer', '~> 3.7', '>= 3.7.6'
```
