### ISSUE TITLE
 DataCite Metadata Schema 4.1 documentation nameType attribute bug

### ISSUE THREAD

**Issue by mpbraendle** [datacite/schema#44]
https://schema.datacite.org/meta/kernel-4.1/doc/DataCite-MetadataKernel_v4.1.pdf 

has typos in the nameType attribute values.

https://schema.datacite.org/meta/kernel-4.1/include/datacite-nameType-v4.1.xsd lists "Personal" and "Organizational" (with z) as enumeration values.

The PDF lists "Organisational" (with s) on p. 14, table row 2.1.1, and p. 22, table row 7.7 . Please correct to "Organizational".

**Comment by mfenner** [comment]
Fixed.
