### ISSUE TITLE
ORCID representation in DataCite XML

### ISSUE THREAD

**Issue by MicheleMorelli** [datacite/schema#47]
Hi All,

I wanted to ask your opinion on 2 issues related to the way ORCIDs are represented in DataCite XML files.

1)
The examples provided on the Datacite website (e.g. https://schema.datacite.org/meta/kernel-4.1/example/datacite-example-full-v4.1.xml ) seem to indicate that the ORCID value needs to be represented in the dddd-dddd-dddd-dddd format. 

However, the new ORCID guidance (https://support.orcid.org/knowledgebase/articles/116780) says that:

> When stored, the ORCID iD should be expressed as a full https URI: https://orcid.org/xxxx-xxxx-xxxx-xxxx, complete with the protocol (https://), and with hyphens in the identifier (xxxx-xxxx-xxxx-xxxx).

Is the value of the ORCID field in the Datacite XML going to continue being expressed in the current format, or do you reckon that the new format suggested by ORCID will be adopted?

2)
The current schemeURI is "http://orcid.org/" - will it be changed to 'https://orcid.org/'? Can the https URI be used?

Thank you,
Michele

**Comment by mfenner** [comment]
@MicheleMorelli we recommend to follow ORCID's recommendation, using the format `https://orcid.org/xxxx-xxxx-xxxx-xxxx`. We will continue to support `http://orcid.org/xxxx-xxxx-xxxx-xxxx` and `xxxx-xxxx-xxxx-xxxx` to not break existing DOI metadata. 

We need to update our documentation and examples in some places. The documentation for Schema 4.1 makes it clear that the ORCID guidance should be followed.

**Comment by MicheleMorelli** [comment]
@mfenner Thank you very much for the prompt response.
