### ISSUE TITLE
Affiliations should have optional identifiers

### ISSUE THREAD

**Issue by nichtich** [datacite/schema#48]
Affiliations are plain dump strings. It should be allowed to add identifiers e.g. GRID, ORCID, VIAF, GND... for the organization.

**Comment by mfenner** [comment]
This is planned for the next major schema release in 2019 (schema 4.2 is basically ready and will be released very soon), aligned with the work described in https://blog.datacite.org/org-id-recap-and-hint-of-things/.

**Comment by nichtich** [comment]
@mfenner [at twitter you wrote](https://twitter.com/mfenner/status/1039492597415333888) there is no 4.2 draft yet, so what's the case? I'd like to know a rough estimate when to expect 4.2 (end of the year would be fine) and whether it will also allow non-DOI URIs as identifier (of course not for DOI registration but for othe kinds of records) so I could proceed with [mapping DataCite XML to Schema.org](https://github.com/gbv/lazar.gbv.de/blob/master/xslt/datacite2schema.xsl).

**Comment by mfenner** [comment]
@nichtich there is internal discussion by the DataCite Metadata WG, but no single public document yet. 4.2 will be released before the end of the year. Please open a separate issue about the other question.

**Comment by mfenner** [comment]
@nichtich as I am sure you have seen by now, we released schema 4.2 in March: https://doi.org/10.5438/wvkv-fz40. Non-DOI identifiers are permitted in the schema.

Affiliation identifiers will be added in schema 4.3, which will be a minor update before the end of the year.
