### ISSUE TITLE
Fix broken links in schema website

### ISSUE THREAD

**Issue by mfenner** [datacite/schema#54]

**Comment by richardhallett** [comment]
URL        `example/datacite-example-relationTypeIsIdenticalTo-v3.0.xml'
Name       `Example with IsIdenticalTo as related resource'
Parent URL https://schema.datacite.org/meta/kernel-3.0/, line 175, col 5
Real URL   https://schema.datacite.org/meta/kernel-3.0/example/datacite-example-relationTypeIsIdenticalTo-v3.0.xml
Check time 3.293 seconds
Size       601B
Result     Error: 404 Not Found

URL        `doc/DataCite-MetadataKernel_v2.2.pdf'
Name       `Download PDF'
Parent URL https://schema.datacite.org/meta/kernel-2.1/, line 164, col 4
Real URL   https://schema.datacite.org/meta/kernel-2.1/doc/DataCite-MetadataKernel_v2.2.pdf
Check time 2.952 seconds
Size       578B
Result     Error: 404 Not Found

**Comment by richardhallett** [comment]
Fixed links
