### ISSUE TITLE
Need a distribution concept

### ISSUE THREAD

**Issue by smrgeoinfo** [datacite/schema#64]
Since sizes and formats (and perhaps language, versions, descriptions...) are specific to different distributions,  it would make a much better metadata scheme if there were a distributions metadata element. I.e. align with DCAT...

**Comment by mfenner** [comment]
Completely agree, and this has been discussed by the DataCite Metadata Working Group. The challenge is breaking changes, best reserved for major schema versions like the upcoming schema 5.0 (we will be releasing 4.3 in August).

**Comment by smrgeoinfo** [comment]
I can see the breaking change is a big problem... still, hope it makes it in v5.0  
thanks

**Comment by mfenner** [comment]
You can give the idea some weight by suggesting it on our public roadmap at https://datacite.org/roadmap.html
