### ISSUE TITLE
JSON and JSON Schema 4.3

### ISSUE THREAD

**Issue by tmorrell** [datacite/schema#67]
Take existing XML examples and add JSON examples.  Modify 4.2 JSON Schema with new options.

I've got this on my list, unless someone else gets it done first.

**Comment by mfenner** [comment]
It is easy for me to convert the XML examples for schema 4.3 using the `bolognese` gem/command line tool. Do you have an easy way to generate the JSON examples?

**Comment by tmorrell** [comment]
I can do the conversion once I implement 4.3 in Python, but if you generate them I'll have something to test with.  Either way is fine!

**Comment by mfenner** [comment]
Schema 4.3 examples added at https://github.com/datacite/schema/tree/master/source/json/kernel-4.3/example

**Comment by mfenner** [comment]
Many examples are the same as for 4.2, but a few use the new affiliation identifier metadata. In contrast to the XML this is a breaking change in the JSON, as affiliation is now an array of objects instead of an array of strings.

**Comment by tmorrell** [comment]
Thanks @mfenner!  The examples and schema validated well, except for two small changes I put in https://github.com/datacite/schema/pull/69
