### ISSUE TITLE
Description problem for relatedItem/number

### ISSUE THREAD

**Issue by acraugh** [datacite/schema#90]
Noticed a typo in a documentation field in the new <relatedItem> element. The xs:documentation string for <number> (line 521) is identical to the xs:documentation string for <issue> (line 516). The description for <number> in the draft schema documentation, corrected for typos, is: 

> Number of the related item, e.g., report number or article number.

**Comment by KellyStathis** [comment]
I think this was corrected in the final 4.4 metadata.xsd.
