### ISSUE TITLE
How to use schema with non-standard formats

### ISSUE THREAD

**Issue by jcoyne** [datacite/schema#96]
I'm having trouble making use of the schema because these formats are not in the set that is defined in the JSON Schema spec:
https://github.com/datacite/schema/blob/master/source/json/kernel-4.3/datacite_4.3_schema.json#L73-L82

**Comment by KellyStathis** [comment]
@tmorrell @lnielsen - do you have any insight on how these formats are defined?

**Comment by KellyStathis** [comment]
@tmorrell has opened an issue for this here: https://github.com/inveniosoftware/datacite/issues/76. 

I'm going to close this issue as Invenio will be better able to answer this question on the JSON schema.
